### ISSUE TITLE
Using Product Family Handle in Place of ID Not Working

### ISSUE THREAD

**Issue by emnC5117** [maxio-com/ab-typescript-sdk#86] opened 2024-09-24 12:51 UTC
For the productFamiliesController.listProductsForProductFamily, using the productFamilyHandle in place of the productFamilyId does not work. The problem appears to be with the endpoint itself and not with the package. The endpoint is not found using the format below. According to the docs, this should work.

productFamiliesController.listProductsForProductFamily({productFamilyId: `handle:${productFamilyHandle}`})

https://{site}.chargify.com/product_families/handle:{productFamilyHandle}/products.json

For the readProductFamily method, the id parameter is typed as a number and it doesn't even try to make the request.

You can make the request to the endpoint like either of the examples below.

https://{site}.chargify.com/product_families/handle:{productFamilyHandle}.json
https://{site}.chargify.com/product_families/{id}.json

According to the documentation, both methods should accept `handle:${productFamilyHandle}` in place of the productFamilyId.

(using v5.0.0)

**Comment by emnC5117** [comment] 2024-10-09 17:06
This is still not working as expected as of v5.1.0

**Comment by maciej-nedza** [comment] 2024-10-18 09:25
Yes @emnC5117 we're aware, I'm sorry. It's an api issue and we're waiting for the responsible team to pick it up. I'll let you know once it's resolved. Once it is, it won't require sdk update to support this change

**Comment by maciej-nedza** [comment] 2024-11-26 07:46
@emnC5117 the issue is finally fixed on the backend side. Now it should work even without updating local sdk version.

**Closed by maciej-nedza** 2024-11-26 07:46 UTC
